services:
  web:
    build:
      context: .
    container_name: "web-task"
    command: gunicorn --bind 0.0.0.0:8008 core.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000" # 8008:8008
    depends_on:
      - db
    restart: always


  db:
    image: postgres
    container_name: "postgres-db-task"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - .env

    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER} -d $${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  nginx:
    image: nginx:latest
    container_name: "nginx-task"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx konfiguratsiya fayli
      - ./static:/app/static  # Statik fayllar
      - ./media:/app/media  # Media fayllar
    ports:
      - "8008:8008"  # 80-portni tashqi olamga ochish
    depends_on:
      - web
    restart: always

volumes:
  db_data:
  static:
  media: